'use client';
import { useEffect, useState } from 'react';
import { createClient } from '@/lib/supabase/client';

type Product={id:string;name:string;sku:string;selling_price:number;stock:number;unit:string;minimum_stock:number};
export default function Products(){const [products,setProducts]=useState<Product[]>([]);const [search,setSearch]=useState('');const [name,setName]=useState('');const [sku,setSku]=useState('');const [price,setPrice]=useState('');const [error,setError]=useState('');const [loading,setLoading]=useState(true);const db=createClient();
async function load(){setLoading(true);const {data:user}=await db.auth.getUser();if(!user.user){location.href='/login';return}const {data:membership}=await db.from('tenant_users').select('tenant_id').eq('user_id',user.user.id).limit(1).maybeSingle();if(!membership){setError('Akun belum memiliki tenant. Selesaikan onboarding terlebih dahulu.');setLoading(false);return}const {data,error}=await db.from('products').select('id,name,sku,selling_price,stock,unit,minimum_stock').eq('tenant_id',membership.tenant_id).eq('active',true).order('name');if(error)setError(error.message);setProducts((data as Product[])||[]);setLoading(false)}
useEffect(()=>{load()},[]);
async function add(){setError('');const {data:user}=await db.auth.getUser();const {data:membership}=await db.from('tenant_users').select('tenant_id').eq('user_id',user.user?.id||'').limit(1).maybeSingle();if(!membership){setError('Tenant belum tersedia.');return}const {error}=await db.from('products').insert({tenant_id:membership.tenant_id,name,sku,selling_price:Number(price||0),purchase_price:0,stock:0,minimum_stock:0,unit:'pcs'});if(error)setError(error.message);else{setName('');setSku('');setPrice('');load()}}
const filtered=products.filter(p=>(p.name+' '+p.sku).toLowerCase().includes(search.toLowerCase()));return <main className="min-h-screen"><header className="border-b bg-white px-6 py-5"><p className="text-sm text-black/50">Master data</p><h1 className="font-serif text-3xl">Produk</h1></header><section className="mx-auto max-w-7xl p-6"><div className="mb-6 rounded-2xl bg-white p-5"><h2 className="font-semibold">Tambah produk</h2><div className="mt-4 grid gap-3 md:grid-cols-4"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Nama produk" className="rounded-xl border p-3"/><input value={sku} onChange={e=>setSku(e.target.value)} placeholder="SKU" className="rounded-xl border p-3"/><input value={price} onChange={e=>setPrice(e.target.value)} placeholder="Harga jual" type="number" className="rounded-xl border p-3"/><button onClick={add} disabled={!name||!sku} className="rounded-xl bg-charcoal p-3 font-semibold text-white disabled:opacity-40">Simpan produk</button></div>{error&&<p className="mt-3 text-sm text-red-600">{error}</p>}</div><div className="rounded-2xl bg-white p-5"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Cari nama atau SKU..." className="mb-5 w-full rounded-xl border p-3 md:max-w-sm"/>{loading?<p>Memuat produk...</p>:filtered.length===0?<p className="py-10 text-center text-black/50">Belum ada produk.</p>:<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-black/50"><th className="p-3">Produk</th><th className="p-3">SKU</th><th className="p-3">Harga jual</th><th className="p-3">Stok</th></tr></thead><tbody>{filtered.map(p=><tr key={p.id} className="border-b"><td className="p-3 font-medium">{p.name}</td><td className="p-3">{p.sku}</td><td className="p-3">Rp {Number(p.selling_price).toLocaleString('id-ID')}</td><td className={`p-3 ${p.stock<=p.minimum_stock?'text-red-600':''}`}>{p.stock} {p.unit}</td></tr>)}</tbody></table></div>}</div></section></main>}
