create type public.payment_method as enum ('CASH','QRIS','TRANSFER','RECEIVABLE','OTHER');
create table public.sales (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id) on delete cascade, branch_id uuid not null references public.branches(id), invoice_no text not null, customer_id uuid, subtotal numeric(14,2) not null default 0, discount numeric(14,2) not null default 0, total numeric(14,2) not null default 0, payment_method public.payment_method not null, paid_amount numeric(14,2) not null default 0, change_amount numeric(14,2) not null default 0, created_by uuid references public.profiles(id), created_at timestamptz not null default now(), unique(tenant_id,invoice_no));
create table public.sale_items (id uuid primary key default gen_random_uuid(), sale_id uuid not null references public.sales(id) on delete cascade, tenant_id uuid not null references public.tenants(id) on delete cascade, product_id uuid not null references public.products(id), product_name text not null, quantity numeric(14,3) not null, unit_price numeric(14,2) not null, discount numeric(14,2) not null default 0, line_total numeric(14,2) not null);
create table public.payments (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id) on delete cascade, sale_id uuid not null references public.sales(id) on delete cascade, method public.payment_method not null, amount numeric(14,2) not null, reference_no text, created_by uuid references public.profiles(id), created_at timestamptz not null default now());
create index sales_tenant_date_idx on public.sales(tenant_id,created_at desc); create index sale_items_product_idx on public.sale_items(tenant_id,product_id);
alter table public.sales enable row level security; alter table public.sale_items enable row level security; alter table public.payments enable row level security;
create policy sales_member on public.sales for all using (public.is_tenant_member(tenant_id)) with check (public.is_tenant_member(tenant_id));
create policy sale_items_member on public.sale_items for all using (public.is_tenant_member(tenant_id)) with check (public.is_tenant_member(tenant_id));
create policy payments_member on public.payments for all using (public.is_tenant_member(tenant_id)) with check (public.is_tenant_member(tenant_id));
