create type public.purchase_status as enum ('PAID','UNPAID','PARTIAL');
create table public.purchases (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id) on delete cascade, branch_id uuid not null references public.branches(id), supplier_id uuid references public.suppliers(id), invoice_no text not null, subtotal numeric(14,2) not null default 0, discount numeric(14,2) not null default 0, total numeric(14,2) not null default 0, status public.purchase_status not null default 'UNPAID', purchased_at timestamptz not null default now(), created_by uuid references public.profiles(id), unique(tenant_id,invoice_no));
create table public.purchase_items (id uuid primary key default gen_random_uuid(), purchase_id uuid not null references public.purchases(id) on delete cascade, tenant_id uuid not null references public.tenants(id) on delete cascade, product_id uuid not null references public.products(id), quantity numeric(14,3) not null, unit_cost numeric(14,2) not null, line_total numeric(14,2) not null);
create table public.expenses (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id) on delete cascade, branch_id uuid not null references public.branches(id), category text not null, amount numeric(14,2) not null, description text, spent_at timestamptz not null default now(), created_by uuid references public.profiles(id));
create index purchases_tenant_date_idx on public.purchases(tenant_id,purchased_at desc); create index expenses_tenant_date_idx on public.expenses(tenant_id,spent_at desc);
alter table public.purchases enable row level security; alter table public.purchase_items enable row level security; alter table public.expenses enable row level security;
create policy purchases_member on public.purchases for all using (public.is_tenant_member(tenant_id)) with check (public.is_tenant_member(tenant_id));
create policy purchase_items_member on public.purchase_items for all using (public.is_tenant_member(tenant_id)) with check (public.is_tenant_member(tenant_id));
create policy expenses_member on public.expenses for all using (public.is_tenant_member(tenant_id)) with check (public.is_tenant_member(tenant_id));
